# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "微言微行"
description: > # this means to ignore newlines until "email:"
   It is a rough road that leads to the heights of greatness.

email: xu_yubo@outlook.com
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/blog_image_1.jpg"

name: 'XuYuBo'
author: 'XuYuBo'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.xyb.space" # the base hostname & protocol for your site
baseurl: ""

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

#fill in disqus shortname to use disqus
#disqus: xyb

# social icons and sharing options
social:
  - icon:	weibo
    url:	http://weibo.com/YuBoXu
    desc: Follow me on weibo
    share_url:
    share_title:
    share_link:

# Data
favicon: img/favicon.png





# Comments
comments :
provider : duoshuo
duoshuo :
short_name : xybspace
disqus :
short_name : xybspace
